name: site
version: 0.1.0.0
synopsis: Personal website of Jonathan Laurent
license: GPL-3
author: Jonathan Laurent
maintainer: jonathan-laurent@live.fr
build-type: Simple

executable:
  source-dirs: src
  main: Main.hs
  ghc-options: -fno-warn-name-shadowing

dependencies:
  - hakyll >= 4.10
  - asciimath
  - base >=4.8
  - mtl
  - containers
  - transformers
  - data-default
  - filepath
  - directory
  - process
  - time
  - binary
  - text
  - yaml
  - scientific
  - vector
  - unordered-containers
  - utf8-string
  - pandoc
  - pandoc-types
  - blaze-html
  - texmath