name: asciimath
version: 0.1.0.0
synopsis: A compiler from a variant of Asciimath to Latex
license: GPL-3
license-file: LICENSE
author: Jonathan Laurent
maintainer: jonathan-laurent@live.fr
category: Text
build-type: Simple
source-dirs: src

dependencies:      
  - base >=4.8
  - containers >= 0.5.6.2
  - directory >= 1.2.2.0
  - parsec >= 3.1.9
  - pretty >= 1.1.2.0

library:
  exposed-modules:
    - AsciiMath

executable:
  main: Main.hs