- what: >
    **External Reviewer** for: LICS 2025, TACAS 2025, IJCAR 2024, ICCPS 2024, NFM 2023, LSFA 2023, LICS 2023, FM 2023, IJCAR 2022, ICCPS 2022, CADE 2021, ICCPS 2020, LICS 2020, FASE 2019, OOPSLA 2018.

- what: >
    **Artifact Evaluation Committee Member** for: SAS 2023.

- when: Spring 2018
  what: >
    **Organizer** of the weekly PL Lunch at Carnegie Mellon University.