- what: >
    External Reviewer for: OOPSLA 2018, FASE 2019, LICS 2020, ICCPS 2020, CADE 2021, ICCPS
    2022, IJCAR 2022, FM 2023, LICS 2023, LSFA 2023, NFM 2023.

- what: >
    Artifact Evaluation Committee member for: SAS 2023.

- when: Spring 2018
  what: >
    Organizer of the weekly PL Lunch at Carnegie Mellon University.